import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../component/Navbar";
import Footer from "../component/Footer";
import ProviderPage from "@/lib/provider/page";
import { Toaster } from "react-hot-toast";
import SmoothScrolling from "@/component/SmoothScrolling";
import ProviderTheme from "./ProviderTheme";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "DocAppoint",
  description: "Generated by create next app",
  icons: {
    icon: '/d.png',
  },
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased bg-background text-foreground`}
    >
      <body className="min-h-full flex flex-col">
        <ProviderTheme>

          <Navbar></Navbar>
        <ProviderPage>
          <SmoothScrolling>
            {children}
          </SmoothScrolling>
        </ProviderPage>
        <Footer></Footer>
        <Toaster />

        </ProviderTheme>
        </body>
    </html>
  );
}
